name: Update README from BoardCaster

on:
  schedule:
    - cron: '*/15 * * * *'  # 每五分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Listener repository
      uses: actions/checkout@v2

    - name: Clone BoardCaster repository
      run: git clone https://github.com/CS-BAOYAN/BoardCaster.git

    - name: Copy and rename output.md to README.md
      run: |
        cp BoardCaster/output.md README.md

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Update README.md from BoardCaster"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
